layout_spectrum: 0.6653692
typography_spectrum: 0.3818896
color:
  saturation: 0.9949518
  lightness: 0.4642455
  brandStrength: 0.459398
  rhythmicContrast: 0.04371917
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Joshj
